from . import add_tag
from . import delete_data
from . import delete_tag
from . import get_data
from . import login
from . import logout
from . import register
from . import reset_demo
from . import restore_data
from . import tags_suggest
from . import who_am_i
